
-- RETRIEVE RECORDS FROM SEVERAL TABLES

SELECT COMPLAINT_ID,(SELECT CUSTOMER_NAME FROM SETUP_CUSTOMER WHERE CUSTOMER_ID = U.CUSTOMER_ID) AS CUSTOMER_NAME, 
		REQUEST, COMPLAINT_CATEGORY, 
		DATE_CREATED, 
	(SELECT STATUS_NAME FROM SETUP_STATUS WHERE STATUS_ID = U.STATUS_ID) AS STATUS_NAME
			FROM SETUP_COMPLAINT U